image: python:latest
test:
  script:
    - pip install simplejson
    - pip install pytagcloud
    - pip install pygame
    - pip install html5lib
    - pip install chardet
    - pip install bs4
    - make test 